# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NJOY
subtitle: Nuclear Data Processing-from Los Alamos National Laboratory
email: njoy@lanl.gov

description: > # this means to ignore newlines until "baseurl:"
  Website for documentation and code for the development of NJOY, a nuclear data 
  processing code from Los Alamos National Laboratory. All source code as part 
  of the NJOY project—including this website—is covered by the BSD, 3-clause 
  license, as detailed in the <a href="/LICENSE.html">license</a> file.

url: "http://njoy.lanl.gov" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  njoy

markdown: kramdown
timezone: America/Denver

theme: minima

# Serving
port: 8000
baseurl: "" # the subpath of your site, e.g. /blog

exclude: [vendor]
include: ['Developers', 'Build', 'LICENSE.md']
