image: 
  -
    Visual Studio 2017
shallow_clone: false
environment:
  machine_user: test_user
  machine_pass: awesomepassword
  CTEST_OUTPUT_ON_FAILURE: 1
  FC: gfortran
  global:
    CYG_ROOT: "C:\\cygwin"
    CYG_MIRROR: "http://cygwin.mirror.constant.com"
    CYG_CACHE: "C:\\cygwin\\var\\cache\\setup"
    CYG_BASH: "C:\\cygwin\\bin\\bash"
  matrix:
    - BUILD_TYPE: debug
      PLATFORM: cygwin
      STATIC_LIBRARIES: false
      CC: gcc
      CXX: g++
    - BUILD_TYPE: release
      PLATFORM: cygwin
      STATIC_LIBRARIES: false
      CC: gcc
      CXX: g++
    - BUILD_TYPE: debug
      PLATFORM: cygwin
      STATIC_LIBRARIES: true
      CC: gcc
      CXX: g++
    - BUILD_TYPE: release
      PLATFORM: cygwin
      STATIC_LIBRARIES: true
      CC: gcc
      CXX: g++
    - BUILD_TYPE: debug
      PLATFORM: cygwin
      STATIC_LIBRARIES: false
      CC: clang
      CXX: clang++
    - BUILD_TYPE: release
      PLATFORM: cygwin
      STATIC_LIBRARIES: false
      CC: clang
      CXX: clang++
    - BUILD_TYPE: debug
      PLATFORM: cygwin
      STATIC_LIBRARIES: true
      CC: clang
      CXX: clang++
    - BUILD_TYPE: release
      PLATFORM: cygwin
      STATIC_LIBRARIES: true
      CC: clang
      CXX: clang++
install:
  - "C:\\cygwin\\setup-x86.exe -q --root \"%CYG_ROOT%\" --site \"%CYG_MIRROR%\" --local-package-dir \"%CYG_CACHE%\" --packages clang,gcc,g++,gcc-fortran,cmake,make,git,python3,tree --force-current"
clone_folder: C:\cygwin\projects\NJOY21
before_build:
  - cd C:\cygwin\projects\NJOY21\
  - set PATH=C:\cygwin\bin;%PATH%
  - bash -c "python3 ./metaconfigure/fetch_subprojects.py"
  - bash -c "mkdir build"
  - cd build
  - bash -c "cmake -D unit_tests=OFF -G \"Unix Makefiles\" -Wsubobject-linkage .."
build_script:
-
    bash -c "make -j2"
test_script:
- 
    bash -c "ctest -j2"
