image: 
  -
    Visual Studio 2017
shallow_clone: true
environment:
  machine_user: test_user
  machine_pass: awesomepassword
  CTEST_OUTPUT_ON_FAILURE: 1
  CC: gcc
  CXX: g++
  FC: gfortran
  global:
    CYG_ROOT: "C:\\cygwin"
    CYG_MIRROR: "http://cygwin.mirror.constant.com"
    CYG_CACHE: "C:\\cygwin\\var\\cache\\setup"
    CYG_BASH: "C:\\cygwin\\bin\\bash"
  matrix:
    - BUILD_TYPE: release
      STATIC_LIBRARIES: false
install:
  - "C:\\cygwin\\setup-x86.exe -q --root \"%CYG_ROOT%\" --site \"%CYG_MIRROR%\" --local-package-dir \"%CYG_CACHE%\" --packages gcc,g++,gfortran,cmake,make,git,python3"
  - cd C:\projects\NJOY21
#  - git submodule update --init --recursive
clone_folder: c:\projects\NJOY21
build_script:
-
    python ./metaconfigure/fetch_subprojects.py 

    python ./metaconfigure/generate.py cmake .

    mkdir build

    cd build

    cmake c:\projects\NJOY21 -G "Visual Studio 15"

    cmake --build . --config "Debug"

test_script:
- cmd:>-
    cd build

    ctest
