version: 0.2

##env:
##  variables:

phases:
  install:
    commands:
      - echo Entered install phase...
      - echo Install starting on $( date )
      - apt purge cmake
      - add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - add-apt-repository -y ppa:george-edison55/cmake-3.x
      - apt update
      - apt upgrade -y
      - apt install -y software-properties-common python-software-properties
      - apt install -y gcc-6 g++-6 gfortran-6 cmake cmake-data git lcov

  pre_build:
    commands:
      - echo Entered pre-build phase...
      - echo Pre-build starting on $( date )
      - mkdir build
      - cd build
      - FC=$( which gfortran )
      - cmake ..

  build:
    commands:
      - echo Entered build phase...
      - echo Build starting on $( date ) on $NPROC cores...
      - make -j$( nproc )
      - echo Running tests...
      - echo Test starting on $( date ) on $NPROC cores...
      - ctest -j$( nproc ) --output-on-failure
      - echo Build and test completed at $( date )
