version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - pwd
      - git pull --recurse-submodules
  build:
    commands:
      - echo Entered the build phase...
      - echo Build phase starting on $( date )
      - chmod +x .AWS/*.sh
      - ls -la .AWS/
      - /bin/bash -c ./.AWS/gnu_build.sh
      - /bin/bash -c ./.AWS/clang_build.sh
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Post-build phase starting on $( date )
